### ISSUE TITLE
Enable passing ssl certificates when creating AuthenticatedClient()

### ISSUE THREAD

**Issue by iamemilio** [gophercloud/utils#105]
Extend the [ClientOpts struct](https://github.com/gophercloud/utils/blob/88c6e9e533261350ec733e2e2147a1d3f8eb62de/openstack/clientconfig/requests.go#L40) to support the addition a string feild, CACert. Then use the cert passed in all following openstack authentication requests.

**Comment by jtopjian** [comment]
@iamemilio Please see https://github.com/gophercloud/utils/pull/99 instead. This will allow an http client to be configured with the appropriate SSL configuration. As an example of that, see here: https://github.com/gophercloud/utils/blob/master/terraform/auth/config.go

Adding SSL data directly to the client will create a tight coupling of the http client and openstack client which we want to avoid in order to allow better flexibility across applications.

**Comment by iamemilio** [comment]
Understood, thanks for informing me before I wasted a lot of time and effort :). This would work just as well for my use case. If there is anything I can contribute to help you get #99 merged please let me know.

**Comment by jtopjian** [comment]
It looks like I need to tweak Travis and possibly drop support for some old Go versions, but other than that, I don't mind merging #99 at all. I should be able to get to that in the next day.

**Comment by jtopjian** [comment]
@iamemilio #99 has been merged.

To take advantage of it, create and configure an [`http.Client`](https://golang.org/pkg/net/http/#Client) struct with TLS via [`http.Transport`](https://golang.org/pkg/net/http/#Transport). If you aren't familiar with how to do this, it's all native to Golang and nothing specific to Gophercloud, so any external resource can help. We have some examples here:

* https://github.com/gophercloud/utils/blob/master/acceptance/openstack/clientconfig/clientconfig_test.go#L64-L73
* https://github.com/gophercloud/utils/blob/master/terraform/auth/config.go#L164-L214

But they're also doing some extra things like configuring a RoundTripper to print REST debug info.

But once you have your `http.Client` set up correctly, you can then pass it via the new `ClientOpts` field.

The next part gets a little tricky. If you're using the [`NewServiceClient`](https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/requests.go#L701) convenience function, then everything is handled automatically. But if the application you're working on isn't able to leverage `NewServiceClient` (which is totally fine - `NewServiceClient` is only meant to handle common cases), then you'll need to do the next step yourself, but fortunately it's simple: just do this:

https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/requests.go#L743-L746

Basically just pass `opts.HTTPClient` to the _provider_ client's `HTTPClient` field.

Once that is in place, then all HTTP requests will leverage the SSL configuration.

If you need the SSL configuration for SSL/TLS client authentication, I don't think `NewServiceClient` will work since the provider client is created before `HTTPClient` is passed - I might need to revisit that. Instead, try following closely with the Terraform auth code linked above (even outside the highlighted areas). The highlighted chunk of code began specifically to support SSL/TLS client auth, so it should be done in a way where the client is set up correctly before any initial HTTP request is made, thus allowing a provider client to be authenticated properly. At least, no one has reported it _doesn't_ work :slightly_smiling_face: 

Please let me know if you have any questions or run into any problems.
